server:
  port: 10000
spring:
  application:
    name: SCW-WEBUI
  thymeleaf:
    prefix: classpath:/templates/   #在构建URL时预先查看名称的前缀
    suffix: .html  #构建URL时附加到查看名称的后缀
    cache: false #禁用模板缓存
  redis:
    host: 10.10.9.194
    port: 6379
    password: 123
  session:
    store-type: redis #session存储方式
    timeout: PT30M    #session过期时间 单位：秒
  mvc:
    hiddenmethod:
      filter:
        enabled: true
feign:
  hystrix:
    enabled: true  #开启Feign的熔断功能
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com:
      offcn: debug